name: CI/CD Roman Converter

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test-lint-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install ESLint
      run: npm install eslint

    - name: Lint JavaScript
      run: npx eslint script.js || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .

